kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: hpa-backend
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  targetCPUUtilizationPercentage: 30
