kind: Pod
apiVersion: v1
metadata:
  name: backend
  namespace: default
spec:
  containers:
  - image: mysql:latest
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "password"
  - image: nico989/ubuntu-flask:v1
    name: ubuntu
    command: ["/bin/sleep", "3650d"]
