apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nico989/ubuntu-flask:v1
        name: ubuntu
        resources: {}
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-ecx"
        - |
          python3 /root/Desktop/webServer/webServer.py
        volumeMounts:
        - name: volume
          mountPath: /root/Desktop/
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mypvc
      hostname: backend
---
apiVersion: v1
kind: Service
metadata:
  name: "backend"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    targetPort: 5000
  selector:
    app: backend
