apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nico989/mysql:v1
        name: mysql
        resources: {}
        ports:
          - name: mysql-internal
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: volume
            mountPath: /var/lib/mysql/
      - image: nico989/ubuntu-flask:v3
        name: ubuntu
        resources: {}
        ports:
          - name: flask-internal
            containerPort: 5000
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-ecx"
        - |
          python3 /root/Desktop/webServer.py
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: storedb
      hostname: backend
---
apiVersion: v1
kind: Service
metadata:
  name: "backend"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
    targetPort: 5000
  selector:
    app: backend
