apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storedb
  labels:
    app: storedb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
